### ISSUE TITLE
Global lsp

### ISSUE THREAD

**Issue by noahfraiture** [mrnossiom/wakatime-lsp#1]
Hello,
In the readme it's said that there's a way to put global lsp but I don't see a way. Is there a way to have global lsp ? Or are there people working on it ?

**Comment by mrnossiom** [comment]
Nice catch. The README's wrong indeed. It's currently NOT possible to add global LSPs, but only to configure it per language.
See linked blocking Helix PR: https://github.com/helix-editor/helix/pull/9318.

**Comment by noahfraiture** [comment]
And did you find a way to add an lsp to default lsp ? I have to rewrite the default configuration for every language to add this which can be pretty heavy

**Comment by mrnossiom** [comment]
My config looks like this:
```toml
[[language]]
name = "rust"
language-servers = ["rust-analyzer", "wakatime"]

[[language]]
name = "nix"
language-servers = ["nil", "wakatime"]
auto-format = true

[[language]]
name = "markdown"
language-servers = ["marksman", "wakatime"]

# more stuff
```

Helix actually does merge with default config but does not merge with default LSPs so you have to specify them yourself.
